### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by mcyydscc** [puckk/CTFd-Plugin-unique-token#1]
Please consider changing "/admin-solve/<token>/<challenge_name>" to "challenge_id" in this project, as there may be situations where the challenge names are the same.

**Comment by puckk** [comment]
Hi,

Thank you for the suggestion. We're aware of the potential for duplicate challenge names. However, using challenge names over IDs was a deliberate design choice to avoid dependency on IDs, especially since they can vary across CTFd instances when created via API. We believe this approach offers more flexibility, but we'll keep your feedback in mind for future updates.

Thanks!
